DROP SEQUENCE DB001.SEQ_PRODUTO;
DROP SEQUENCE DB001.SEQ_PEDIDO;
DROP SEQUENCE DB001.SEQ_CLIENTE;
DROP SEQUENCE DB001.SEQ_CATEGORIA;
DROP SEQUENCE DB001.SEQ_CIDADE;

DROP TABLE DB001.ITEM;
DROP TABLE DB001.PRODUTO;
DROP TABLE DB001.PEDIDO;
DROP TABLE DB001.CLIENTE;
DROP TABLE DB001.CATEGORIA;
DROP TABLE DB001.CIDADE;
DROP SCHEMA DB001 RESTRICT;

CREATE SCHEMA DB001;

CREATE SEQUENCE DB001.SEQ_CIDADE
	START WITH 5
	INCREMENT BY 1;

CREATE SEQUENCE DB001.SEQ_CLIENTE
	START WITH 12
	INCREMENT BY 1;

CREATE SEQUENCE DB001.SEQ_CATEGORIA
	START WITH 4
	INCREMENT BY 1;

CREATE SEQUENCE DB001.SEQ_PRODUTO
	START WITH 12
	INCREMENT BY 1;

CREATE SEQUENCE DB001.SEQ_PEDIDO
	START WITH 10
	INCREMENT BY 1;

CREATE TABLE DB001.CIDADE (
	COD_CID INTEGER NOT NULL,
	NOME VARCHAR(20) NOT NULL,
	COD_EXCLUSAO SMALLINT NOT NULL,
	PRIMARY KEY  (COD_CID)
) ; 

CREATE TABLE DB001.CLIENTE (
	COD_CLI INTEGER NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	COD_CID INTEGER NOT NULL,
	COD_EXCLUSAO CHAR(1) DEFAULT 'N',
	PRIMARY KEY  (COD_CLI),
	FOREIGN KEY (COD_CID) REFERENCES DB001.CIDADE(COD_CID)
) ; 

CREATE TABLE DB001.CATEGORIA (
	COD_CAT INTEGER NOT NULL,
	DESCR VARCHAR(30) NOT NULL,
	PRIMARY KEY  (COD_CAT)
) ;


CREATE TABLE DB001.PRODUTO (
	COD_PRD INTEGER NOT NULL,
	DESCR VARCHAR(30) NOT NULL,
	PRECO DECIMAL(9,2),
	COD_CAT INTEGER NOT NULL,
	PRIMARY KEY  (COD_PRD),
	FOREIGN KEY (COD_CAT) REFERENCES DB001.CATEGORIA (COD_CAT)
) ;

CREATE TABLE DB001.PEDIDO (
	NRO_PED INTEGER NOT NULL,
	DATA DATE NOT NULL,
	COD_CLI INTEGER,
	PRIMARY KEY  (NRO_PED),
	FOREIGN KEY (COD_CLI) REFERENCES DB001.CLIENTE (COD_CLI)
) ; 

CREATE TABLE DB001.ITEM (
	NRO_PED INTEGER NOT NULL,
	NRO_ITEM INTEGER NOT NULL,
	COD_PRD INTEGER NOT NULL,
	QTDE DECIMAL(5,0) NOT NULL WITH DEFAULT 1,
	PRIMARY KEY  (NRO_PED, NRO_ITEM),
	FOREIGN KEY (NRO_PED) REFERENCES DB001.PEDIDO (NRO_PED),
	FOREIGN KEY (COD_PRD) REFERENCES DB001.PRODUTO (COD_PRD)
) ; 

