DROP TABLE DB001.ITEM;
DROP TABLE DB001.PRODUTO;
DROP TABLE DB001.PEDIDO;
DROP TABLE DB001.CLIENTE;
DROP TABLE DB001.CATEGORIA;
DROP TABLE DB001.CIDADE;
DROP TABLE DB001.CAMPO;
DROP TABLE DB001.TABELA;

DROP DATABASE DB001;

CREATE DATABASE DB001;
USE DB001;

CREATE TABLE DB001.CIDADE (
	COD_CID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,
	COD_EXCLUSAO BOOLEAN DEFAULT false,
	PRIMARY KEY  (COD_CID)
) ; 

CREATE TABLE DB001.CLIENTE (
	COD_CLI INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	COD_CID INT(11) NOT NULL,
	COD_EXCLUSAO CHAR(1) DEFAULT 'N',
	PRIMARY KEY  (COD_CLI),
	FOREIGN KEY (COD_CID) REFERENCES DB001.CIDADE(COD_CID)
) ; 

CREATE TABLE DB001.CATEGORIA (
	COD_CAT INT(11) NOT NULL AUTO_INCREMENT,
	DESCR VARCHAR(30) NOT NULL,
	PRIMARY KEY  (COD_CAT)
) ;


CREATE TABLE DB001.PRODUTO (
	COD_PRD INT(11) NOT NULL AUTO_INCREMENT,
	DESCR VARCHAR(30) NOT NULL,
	PRECO DECIMAL(9,2),
	COD_CAT INT(11) NOT NULL,
	PRIMARY KEY  (COD_PRD),
	FOREIGN KEY (COD_CAT) REFERENCES DB001.CATEGORIA (COD_CAT)
) ;

CREATE TABLE DB001.PEDIDO (
	NRO_PED INT(11) NOT NULL AUTO_INCREMENT,
	DATA DATE NOT NULL,
	COD_CLI INT(11),
	PRIMARY KEY  (NRO_PED),
	FOREIGN KEY (COD_CLI) REFERENCES DB001.CLIENTE (COD_CLI)
) ; 

CREATE TABLE DB001.ITEM (
	NRO_PED INT(11) NOT NULL,
	NRO_ITEM INT(11) NOT NULL,
	COD_PRD INT(11) NOT NULL,
	QTDE DECIMAL(5,0) NOT NULL DEFAULT 1,
	PRIMARY KEY  (NRO_PED, NRO_ITEM),
	FOREIGN KEY (NRO_PED) REFERENCES DB001.PEDIDO (NRO_PED),
	FOREIGN KEY (COD_PRD) REFERENCES DB001.PRODUTO (COD_PRD)
) ; 

CREATE TABLE DB001.TABELA (
	CODIGO_TABELA INT(11) NOT NULL AUTO_INCREMENT,
	TABELA VARCHAR(30) NOT NULL,
	ACAO INT(1)  NOT NULL,
	USUARIO VARCHAR(30) NOT NULL,
	DATA TIMESTAMP NOT NULL,
	PRIMARY KEY (CODIGO_TABELA)
);

CREATE TABLE DB001.CAMPO (
	CODIGO_CAMPO INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO_TABELA INT(11) NULL,
	NOME VARCHAR(30) NOT NULL,
	VALOR_ANTERIOR VARCHAR(2000),
	VALOR_POSTERIOR VARCHAR(2000),
	PRIMARY KEY (CODIGO_CAMPO),
	FOREIGN KEY (CODIGO_TABELA) REFERENCES DB001.TABELA (CODIGO_TABELA)
);
