DROP TABLE IF EXISTS `nucleo`;
DROP TABLE IF EXISTS `tipo_proposta`;

DROP TABLE IF EXISTS `documento`;
DROP TABLE IF EXISTS `documento_versao`;
DROP TABLE IF EXISTS `historico_documento`;
DROP TABLE IF EXISTS `tipo_documento`;
DROP TABLE IF EXISTS `usuario`;
DROP TABLE IF EXISTS `documento_acao`;
DROP TABLE IF EXISTS `documento_situacao`;
DROP TABLE IF EXISTS `documento_template`;

CREATE TABLE `nucleo` (
	`id_nucleo` int(11) not null auto_increment,
	`nome` varchar(50),
	`sigla` varchar(10),
	primary key(`id_nucleo`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE `tipo_proposta` (
	`id_tipo_proposta` int(11) not null,
	`descricao` varchar(50),
	primary key(`id_tipo_proposta`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE `tipo_documento` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;


CREATE TABLE `usuario` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `documento_acao` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;


CREATE TABLE `documento_situacao` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `documento_template` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ARQUIVO` longblob,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE `documento` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_CRIACAO` datetime DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `ID_TIPO_TEMPLATE` int(11) DEFAULT NULL,
  `ID_TIPO_DOCUMENTO` int(11) DEFAULT NULL,
  `ID_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK383D52B477313943` (`ID_USUARIO`),
  KEY `FK383D52B4F96C009A` (`ID_TIPO_TEMPLATE`),
  KEY `FK383D52B46F2BC6B8` (`ID_TIPO_DOCUMENTO`),
  CONSTRAINT `FK383D52B46F2BC6B8` FOREIGN KEY (`ID_TIPO_DOCUMENTO`) REFERENCES `tipo_documento` (`ID`),
  CONSTRAINT `FK383D52B477313943` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID`),
  CONSTRAINT `FK383D52B4F96C009A` FOREIGN KEY (`ID_TIPO_TEMPLATE`) REFERENCES `documento_template` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

CREATE TABLE `documento_versao` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ARQUIVO` longblob,
  `DATA_CHECKOUT` datetime DEFAULT NULL,
  `DATA_CRIACAO` datetime DEFAULT NULL,
  `NOME_ARQUIVO` varchar(255) DEFAULT NULL,
  `VERSAO` float DEFAULT NULL,
  `ID_DOCUMENTO` int(11) DEFAULT NULL,
  `ID_SITUACAO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK1466A54952F8DA8F` (`ID_DOCUMENTO`),
  KEY `FK1466A549ACC67511` (`ID_SITUACAO`),
  CONSTRAINT `FK1466A549ACC67511` FOREIGN KEY (`ID_SITUACAO`) REFERENCES `documento_situacao` (`ID`),
  CONSTRAINT `FK1466A54952F8DA8F` FOREIGN KEY (`ID_DOCUMENTO`) REFERENCES `documento` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `historico_documento` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA` datetime DEFAULT NULL,
  `ID_DOCUMENTO` int(11) DEFAULT NULL,
  `ID_ACAO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK6674012552F8DA8F` (`ID_DOCUMENTO`),
  KEY `FK66740125B27116E3` (`ID_ACAO`),
  CONSTRAINT `FK66740125B27116E3` FOREIGN KEY (`ID_ACAO`) REFERENCES `documento_acao` (`ID`),
  CONSTRAINT `FK6674012552F8DA8F` FOREIGN KEY (`ID_DOCUMENTO`) REFERENCES `documento` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

